package data;

import haxe.io.Path;
import AST.JsdocObject;

using StringTools;

class TypedefObj extends BaseObj {
	public var description:String; // class name

	// public var jsdoc:JsdocObject; // AST generated by JsDoc
	// public var export:String;
	// public var folder:String;

	public function new(obj:JsdocObject) {
		super(obj);
		this.description = (obj.description != null) ? obj.description.replace("* ", "").replace("\n", "\n * ") : "";
		this.className = obj.meta.filename.replace(".js", "");

		// this.jsdoc = obj;

		// this.folder = obj.meta.path.split("Tone/")[1];
		// this.path = Path.join([export, this.folder]);

		this.name = obj.name;
		this.description = (obj.description != null) ? obj.description.replace("* ", "").replace("\n", "\n * ") : "";
	}
}
